name: Build and Deploy to AWS App Runner

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # ✅ Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # ✅ Step 2: Set up Docker Buildx (for multi-arch support)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # ✅ Step 3: Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # ✅ Step 4: Login to Amazon ECR
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
        docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    # ✅ Step 5: Build and Tag Docker Image for Backend
    - name: Build Backend Docker Image
      run: |
        docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.BACKEND_REPOSITORY }}:latest ./backend
        docker tag ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.BACKEND_REPOSITORY }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.BACKEND_REPOSITORY }}:${{ github.sha }}
    
    # ✅ Step 6: Push Docker Images to ECR
    - name: Push Backend Docker Image to ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.BACKEND_REPOSITORY }}:latest
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.BACKEND_REPOSITORY }}:${{ github.sha }}


  deploy-to-apprunner:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    # ✅ Step 8: Deploy Backend to AWS App Runner
    - name: Deploy Backend to AWS App Runner
      run: |
        aws apprunner update-service \
          --service-arn ${{ secrets.BACKEND_SERVICE_ARN }} \
          --source-configuration ImageRepository="{ImageIdentifier=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.BACKEND_REPOSITORY }}:latest,ImageRepositoryType=ECR}"
